/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package playonce;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import static teamgame.teamGame.counter1;
import static teamgame.teamGame.counter2;
import static teamgame.teamGame3.counter3;
import static teamgame.teamGame3.p3;
import teamgame.teamGame4;
import static teamgame.teamGame4.counter4;
/**
 *
 * @author admin
 */
public class playOnce4 extends teamGame4 {

    /**
     * Creates new form playOnce4
     */
    public playOnce4() {
        super();
        setVisible(true);
    }

    public void actionPerformed(ActionEvent e) {
    
    button2 = (JButton) e.getSource();
    
    for(int i=0; i<NUM_BUTTONS; i++){
          
        if(buttons[i].equals(button2))
        {
            buttons[i].setIcon(iconArray[intArray[i]]);
            if(boo == false)
            {
                compare = iconArray[intArray[i]].toString();
                boo = true;
                button3 = button2;
                button4 = button2;
                
            }
            else
            {
                if(compare == iconArray[intArray[i]].toString() && button4 != button2)  
                {
                   if(p1 == true){
                   counter1 = counter1 + 1;
                   p1 = false;
                   p2 = true;
                   }
                   else if(p2 == true){
                      counter2 = counter2 + 1; 
                      p2 = false;
                      p3 = true;
                   }
                   else if(p3 == true){
                       counter3 = counter3 + 1;
                       p3 = false;
                       p4 = true;
                   }
                   else{
                       counter4 = counter4 + 1;
                       p4 = false;
                       p1 = true;
                   }
                
                   faceMatch.setRepeats(false);
                   faceMatch.start();
                   
                   if(p1 == true){
               jButton1.setBackground(Color.GREEN);
               jButton4.setBackground(null);
           }
           else if(p2 == true){
               jButton2.setBackground(Color.GREEN);
               jButton1.setBackground(null);
           }
           else if(p3 == true){
               jButton3.setBackground(Color.GREEN);
               jButton2.setBackground(null);
           }
           else{
               jButton4.setBackground(Color.GREEN);
               jButton3.setBackground(null);
           }
                   
                }
                else if(compare != iconArray[intArray[i]].toString()&& button4!= button2)
                {
                    if(p1 == true){
                     p1 = false;
                     p2 = true;
                   }
                   else{
                      if(p2 == true){
                          p2 = false;
                          p3 = true;
                      }
                      else{
                          if(p3 == true){
                            p3 = false;
                            p4 = true;
                          }
                          else{
                              if(p4 == true){
                                  p4 = false;
                                  p1 = true;
                              }
                          }
                      }
                   }
                    hideFace.setRepeats(false);
                    hideFace.start();
                   
                }
                else
                {
                    button4.setIcon(iconArray[intArray[i]]);
                    boo = true;
                    break;
                }
                 boo = false;   
        
              }            
        }
      }
         if((counter1 + counter2 + counter3 + counter4) == 12){
  getContentPane().removeAll();
    repaint();
    winner();
         }   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        
               
}
